export default [
  {
    id: 1,
    name: "Men's Casual Shirt",
    category: "Clothing",
    price: 29.99,
    brand: "Zara",
    stock: 120,
    description: "A comfortable and stylish casual shirt for men.",
    rating: 4.3,
    images: "/Image/shopImg/men's casual shirt.jpg",
  },
  {
    id: 2,
    name: "Women's Summer Dress",
    category: "Clothing",
    price: 49.99,
    brand: "H&M",
    stock: 80,
    description: "A light and breezy summer dress for women.",
    rating: 4.5,
    images: "/Image/shopImg/Women's Summer Dress.avif",
  },
  {
    id: 3,
    name: "Apple iPhone 14",
    category: "Electronics",
    price: 999.99,
    brand: "Apple",
    stock: 50,
    description: "The latest iPhone with cutting-edge features.",
    rating: 4.8,
    images: "/Image/shopImg/iphone 14.webp",
  },
  {
    id: 4,
    name: "Samsung Galaxy S23",
    category: "Electronics",
    price: 899.99,
    brand: "Samsung",
    stock: 75,
    description: "A premium smartphone with a stunning display.",
    rating: 4.7,
    images: "/Image/shopImg/samsung galaxy 23.webp",
  },
  {
    id: 5,
    name: "Sony WH-100X Headphones",
    category: "Electronics",
    price: 349.99,
    brand: "Sony",
    stock: 100,
    description: "Industry-leading noise-canceling headphones.",
    rating: 4.5,
    images: "/Image/shopImg/Sony WH-100X Headphones.jpg",
  },
  {
    id: 6,
    name: "Dell XPS 13 Laptop",
    category: "Electronics",
    price: 1299.99,
    brand: "Dell",
    stock: 30,
    description: "A sleek and powerful laptop for professionals.",
    rating: 4.5,
    images: "/Image/shopImg/Dell XPS 13 Laptop.jpg",
  },
  {
    id: 7,
    name: "Men's Running Shoes",
    category: "Footwear",
    price: 79.99,
    brand: "Nike",
    stock: 150,
    description: "High-performance running shoes for men.",
    rating: 4.4,
    images: "/Image/shopImg/Men's Running Shoes.jpg",
  },
  {
    id: 8,
    name: "Women's Casual Sneakers",
    category: "Footwear",
    price: 69.99,
    brand: "Adidas",
    stock: 200,
    description: "Comfortable and stylish sneakers for women.",
    rating: 4.5,
    images: "/Image/shopImg/Women's Casual Sneakers.jpg",
  },
  {
    id: 9,
    name: "Men's Analog Watch",
    category: "Watches",
    price: 199.99,
    brand: "Fossil",
    stock: 50,
    description: "A classic analog watch with a leather strap.",
    rating: 4.5,
    images: "/Image/shopImg/Men's Analog Watch.jpg",
  },
  {
    id: 10,
    name: "Women's Digital Watch",
    category: "Watches",
    price: 149.99,
    brand: "Casio",
    stock: 60,
    description: "A trendy digital watch with multiple features.",
    rating: 4.6,
    images: "/Image/shopImg/Women's Digital Watch.jpg",
  },
  {
    id: 11,
    name: "Children's Toy Set",
    category: "Toys",
    price: 39.99,
    brand: "LEGO",
    stock: 100,
    description: "A fun and educational building toy set for kids.",
    rating: 4.8,
    images: "/Image/shopImg/Children's Toy Set.jpg",
  },
  {
    id: 12,
    name: "Men's Wallet",
    category: "Accessories",
    price: 24.99,
    brand: "Tommy Hilfiger",
    stock: 180,
    description: "A sleek leather wallet with multiple compartments.",
    rating: 4.5,
    images: "/Image/shopImg/Men's Wallet.jpg",
  },
  {
    id: 13,
    name: "Women's Handbag",
    category: "Accessories",
    price: 89.99,
    brand: "Michael Kors",
    stock: 70,
    description: "A stylish handbag with ample storage.",
    rating: 4.5,
    images: "/Image/shopImg/Women's Handbag.jpg",
  },
  {
    id: 14,
    name: "Wireless Bluetooth Speaker",
    category: "Electronics",
    price: 59.99,
    brand: "JBL",
    stock: 90,
    description:
      "Portable speaker with powerful sound and Bluetooth connectivity.",
    rating: 4.3,
    images: "/Image/shopImg/Wireless Bluetooth Speake.jpg",
  },
  {
    id: 15,
    name: "Men's Jeans",
    category: "Clothing",
    price: 49.99,
    brand: "Levi's",
    stock: 140,
    description: "Comfortable and durable denim jeans for men.",
    rating: 4.4,
    images: "/Image/shopImg/Men's Jeans.jpg",
  },
  {
    id: 16,
    name: "Women's Yoga Pants",
    category: "Clothing",
    price: 39.99,
    brand: "Lululemon",
    stock: 110,
    description: "High-performance yoga pants for women.",
    rating: 4.8,
    images: "/Image/shopImg/Women's Yoga Pants.jpg",
  },
  {
    id: 17,
    name: "4K Smart TV",
    category: "Electronics",
    price: 499.99,
    brand: "LG",
    stock: 45,
    description: "A stunning 4K Ultra HD Smart TV.",
    rating: 4.1,
    images: "/Image/shopImg/4K Smart TV.jpg",
  },
  {
    id: 18,
    name: "Gaming Laptop",
    category: "Electronics",
    price: 1499.99,
    brand: "Asus",
    stock: 25,
    description: "A high-performance gaming laptop.",
    rating: 4.2,
    images: "/Image/shopImg/game laptop.webp",
  },
  {
    id: 19,
    name: "Kitchen Blender",
    category: "Home Appliances",
    price: 89.99,
    brand: "Ninja",
    stock: 85,
    description: "A powerful blender for smoothies and more.",
    rating: 4.7,
    images: "/Image/shopImg/Kitchen Blender.jpg",
  },
  {
    id: 20,
    name: "Men's Dress Shoes",
    category: "Footwear",
    price: 99.99,
    brand: "Clarks",
    stock: 60,
    description: "Elegant dress shoes for formal occasions.",
    rating: 4.5,
    images: "/Image/shopImg/Men's Dress Shoes.jpg",
  },
  {
    id: 21,
    name: "Women's High Heels",
    category: "Footwear",
    price: 89.99,
    brand: "Jimmy Choo",
    stock: 50,
    description: "Stylish high heels for evening events.",
    rating: 4.6,
    images: "/Image/shopImg/Women's High Heels.jpg",
  },
  {
    id: 22,
    name: "Men's Aviator Sunglasses",
    category: "Accessories",
    price: 149.99,
    brand: "Ray-Ban",
    stock: 70,
    description: "Classic aviator sunglasses with polarized lenses.",
    rating: 4.8,
    images: "/Image/shopImg/Men's Aviator Sunglasses.jpg",
  },
  {
    id: 23,
    name: "Women's Scarf",
    category: "Accessories",
    price: 29.99,
    brand: "Burberry",
    stock: 120,
    description: "A luxurious scarf made from soft materials.",
    rating: 4.5,
    images: "/Image/shopImg/Women's Scarf.jpg",
  },
  {
    id: 24,
    name: "Men's Backpack",
    category: "Accessories",
    price: 79.99,
    brand: "The North Face",
    stock: 95,
    description: "Durable backpack for outdoor adventures.",
    rating: 4.6,
    images: "/Image/shopImg/Men's Backpack.jpg",
  },
  {
    id: 25,
    name: "Coffee Maker",
    category: "Home Appliances",
    price: 79.99,
    brand: "Keurig",
    stock: 80,
    description: "Single-serve coffee maker with multiple brew sizes.",
    rating: 4.5,
    images: "/Image/shopImg/Coffee Maker.jpg",
  },
  {
    id: 26,
    name: "Microwave Oven",
    category: "Home Appliances",
    price: 119.99,
    brand: "Panasonic",
    stock: 60,
    description: "A powerful microwave with smart cooking technology.",
    rating: 4.5,
    images: "/Image/shopImg/Microwave Oven.jpg",
  },
  {
    id: 27,
    name: "Air Fryer",
    category: "Home Appliances",
    price: 129.99,
    brand: "Philips",
    stock: 75,
    description: "A versatile air fryer for healthy cooking.",
    rating: 4.6,
    images: "/Image/shopImg/Air Fryer.jpg",
  },
  {
    id: 28,
    name: "Men's Puffer Jacket",
    category: "Clothing",
    price: 129.99,
    brand: "Columbia",
    stock: 40,
    description: "Warm and lightweight puffer jacket for men.",
    rating: 4.7,
    images: "/Image/shopImg/Men's Puffer Jacket.jpg",
  },
  {
    id: 29,
    name: "Women's Winter Coat",
    category: "Clothing",
    price: 149.99,
    brand: "North Face",
    stock: 50,
    description: "A stylish and warm winter coat for women.",
    rating: 4.8,
    images: "/Image/shopImg/Women's Winter Coat.jpg ",
  },
  {
    id: 30,
    name: "Gaming Console",
    category: "Electronics",
    price: 499.99,
    brand: "Sony",
    stock: 40,
    description: "Next-gen gaming console with stunning graphics.",
    rating: 4.9,
    images: "/Image/shopImg/Gaming Console.jpg",
  },
  {
    id: 31,
    name: "Fitness Tracker",
    category: "Electronics",
    price: 99.99,
    brand: "Fitbit",
    stock: 150,
    description: "Track your fitness and health metrics with ease.",
    rating: 4.4,
    images: "/Image/shopImg/Fitness Tracker.jpg",
  },
  {
    id: 32,
    name: "Wireless Earbuds",
    category: "Electronics",
    price: 149.99,
    brand: "Bose",
    stock: 80,
    description: "High-quality wireless earbuds with noise-canceling features.",
    rating: 4.6,
    images: "/Image/shopImg/Wireless Earbuds.avif",
  },
  {
    id: 33,
    name: "Electric Toothbrush",
    category: "Personal Care",
    price: 59.99,
    brand: "Oral-B",
    stock: 90,
    description: "Advanced electric toothbrush for a thorough clean.",
    rating: 4.5,
    images: "/Image/shopImg/Electric Toothbrush.avif",
  },
  {
    id: 34,
    name: "Men's Leather Belt",
    category: "Accessories",
    price: 34.99,
    brand: "Calvin Klein",
    stock: 100,
    description: "A durable leather belt for men.",
    rating: 4.5,
    images: "/Image/shopImg/Men's Leather Belt.jpg",
  },
  {
    id: 35,
    name: "Women's Pearl Necklace",
    category: "Jewelry",
    price: 199.99,
    brand: "Tiffany & Co.",
    stock: 40,
    description: "A stunning pearl necklace for special occasions.",
    rating: 4.7,
    images: "/Image/shopImg/Women's Pearl Necklace.jpg",
  },
  {
    id: 36,
    name: "Men's Cologne",
    category: "Fragrance",
    price: 89.99,
    brand: "Hugo Boss",
    stock: 70,
    description: "A bold and masculine fragrance for men.",
    rating: 4.6,
    images: "/Image/shopImg/Men's Cologne.jpg",
  },
  {
    id: 37,
    name: "Women's Perfume",
    category: "Fragrance",
    price: 99.99,
    brand: "Chanel",
    stock: 50,
    description: "A timeless and elegant fragrance for women.",
    rating: 4.7,
    images: "/Image/shopImg/Women's Perfume.jpg",
  },
  {
    id: 38,
    name: "Men's Running Shoes",
    category: "Footwear",
    price: 129.99,
    brand: "Adidas",
    stock: 90,
    description: "Comfortable and lightweight running shoes.",
    rating: 4.7,
    images: "/Image/shopImg/Men's Running Shoes.jpg",
  },
  {
    id: 39,
    name: "Women's Yoga Pants",
    category: "Clothing",
    price: 59.99,
    brand: "Lululemon",
    stock: 110,
    description: "High-quality yoga pants for maximum comfort.",
    rating: 4.7,
    images: "/Image/shopImg/Women's Yoga Pants.jpg",
  },
  {
    id: 40,
    name: "Men's Wallet",
    category: "Accessories",
    price: 49.99,
    brand: "Tommy Hilfiger",
    stock: 100,
    description: "A stylish and practical wallet for men.",
    rating: 4.5,
    images: "/Image/shopImg/Men's Wallet.jpg",
  },
  {
    id: 41,
    name: "Men's Laptop Bag",
    category: "Accessories",
    price: 99.99,
    brand: "Samsonite",
    stock: 80,
    description: "A durable and stylish laptop bag for professionals.",
    rating: 4.7,
    images: "/Image/shopImg/Men's Laptop Bag.jpg",
  },
  {
    id: 42,
    name: "Men's Shaving Kit",
    category: "Personal Care",
    price: 59.99,
    brand: "Gillette",
    stock: 70,
    description: "A comprehensive shaving kit for men.",
    rating: 4.7,
    images: "/Image/shopImg/Men's Shaving Kit.jpg",
  },
  {
    id: 43,
    name: "Women's Handbag",
    category: "Accessories",
    price: 199.99,
    brand: "Michael Kors",
    stock: 60,
    description: "A stylish and spacious handbag for everyday use.",
    rating: 4.8,
    images: "/Image/shopImg/Women's Handbag2.jpg",
  },
  {
    id: 44,
    name: "Men's Leather Jacket",
    category: "Clothing",
    price: 299.99,
    brand: "Schott NYC",
    stock: 40,
    description: "A premium leather jacket for men.",
    rating: 4.7,
    images: "/Image/shopImg/Men's Leather Jacket.avif",
  },
  {
    id: 45,
    name: "Men's Golf Set",
    category: "Sports",
    price: 599.99,
    brand: "Callaway",
    stock: 20,
    description: "A complete golf set for enthusiasts.",
    rating: 4.9,
    images: "/Image/shopImg/Men's Golf Set.jpg",
  },
  {
    id: 46,
    name: "Women's Tennis Racket",
    category: "Sports",
    price: 149.99,
    brand: "Wilson",
    stock: 50,
    description: "A lightweight and durable tennis racket for women.",
    rating: 4.1,
    images: "/Image/shopImg/Women's Tennis Racket.jpg",
  },
  {
    id: 47,
    name: "Men's Smartwatch",
    category: "Electronics",
    price: 299.99,
    brand: "Garmin",
    stock: 97,
    description: "A feature-packed smartwatch for active lifestyles.",
    rating: 4.8,
    images: "/Image/shopImg/Men's Smartwatch.jpg",
  },
  {
    id: 48,
    name: "DSLR Camera",
    category: "Electronics",
    price: 1299.99,
    brand: "Dell",
    stock: 25,
    description:
      "Capture stunning, high-resolution images with our top-rated DSLR cameras. ",
    rating: 4.6,
    images: "/Image/shopImg/DSLR Camera.jpg",
  },
  {
    id: 49,
    name: "Dell XPS 13 Laptop",
    category: "Electronics",
    price: 1749,
    brand: "Dell",
    stock: 99,
    description: "Laptop Dell Latitude 5310 Core I5-10310u 256 Ssd 8gb Touch",
    rating: 4.6,
    images: "/Image/shopImg/Dell XPS 13 Laptop2.jpg",
  },
  {
    id: 50,
    name: "Hats",
    category: "Electronics",
    price: 300,
    brand: "Dell",
    stock: 70,
    description: "Vintage Plaid Gentleman Hats",
    rating: 4.6,
    images: "/Image/shopImg/Hats.jpg",
  },
  {
    id: 51,
    name: "PlayStation",
    category: "Electronics",
    price: 900,
    brand: "Dell",
    stock: 10,
    description:
      "PlayStation is offering immersive graphics, lightning-fast performance.",
    rating: 4.2,
    images: "/Image/shopImg/PlayStation.avif",
  },
  ,
];
